### ISSUE TITLE
Give this repo a Gemfile.

### ISSUE THREAD

**Issue by hab278** [Amay22/Siteleaf-NYUAssets-Guard-Capistrano#1]
Instead of using the nyulibraries_assets repo's gemfile, considering giving this repo a gemfile, and in it include nyulibraries_assets and everything else you would need e.g. Siteleaf and Guard.

**Comment by Amay22** [comment]
I actually deleted the Gemfile before pushing to siteleaf.
I am not using nyulibraries Gemfile.
The script creates a gemfile for guard and removes it after the guard task is done. That way the script is totally automated.
I have presumed that siteleaf is a global pre-installed gem. I'll take care of that on my next commit.

**Comment by hab278** [comment]
Right, you dynamically create a Gemfile? Should totally keep it static, it makes it easier to read and keeps it simple. It also splits out dependencies from code.

**Comment by Amay22** [comment]
Did it. Closing this issue.
